# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1374502998);
user_pref("app.update.lastUpdateTime.background-update-timer", 1374502758);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1374503118);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1374502538);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1374502878);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 14);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20130720030214");
user_pref("browser.slowStartup.averageTime", 1190);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20130720030214");
user_pref("browser.startup.homepage_override.mstone", "25.0a1");
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":4}");
user_pref("browser.tabs.closeWindowWithLastTab", false);
user_pref("browser.tabs.tabMinWidth", 1);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1374588680583");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1374502280583");
user_pref("datareporting.sessions.current.activeTicks", 133);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 736);
user_pref("datareporting.sessions.current.main", 71);
user_pref("datareporting.sessions.current.sessionRestored", 918);
user_pref("datareporting.sessions.current.startTime", "1374502638053");
user_pref("datareporting.sessions.current.totalTime", 1390);
user_pref("datareporting.sessions.currentIndex", 3);
user_pref("datareporting.sessions.previous.0", "{\"s\":1374502280132,\"a\":18,\"t\":87,\"c\":true,\"m\":69,\"fp\":1969,\"sr\":2150}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1374502367591,\"a\":5,\"t\":25,\"c\":true,\"m\":309,\"fp\":1230,\"sr\":1196}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1374502418294,\"a\":35,\"t\":180,\"c\":true,\"m\":69,\"fp\":855,\"sr\":817}");
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "tab-width%40design-noir.de:1.0.1,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:25.0a1");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/Applications/FirefoxNightly.app/Contents/MacOS/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1374327595000,\"rdfTime\":1374327584000}}},{\"name\":\"app-profile\",\"addons\":{\"tab-width@design-noir.de\":{\"descriptor\":\"/Users/fabricio/Library/Application Support/Firefox/Profiles/bpj5zwaq.mini_smd/extensions/tab-width@design-noir.de.xpi\",\"mtime\":1374502368000}}}]");
user_pref("extensions.lastAppVersion", "25.0a1");
user_pref("extensions.lastPlatformVersion", "25.0a1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("gecko.buildID", "20130720030214");
user_pref("gecko.mstone", "25.0a1");
user_pref("general.warnOnAboutConfig", false);
user_pref("gfx.blacklist.webgl.msaa", 4);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 100664);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("toolkit.startup.last_success", 1374502638);
user_pref("toolkit.telemetry.previousBuildID", "20130720030214");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1377094932);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
